<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/9/15
 * Time: 9:00
 */
namespace app\modules\admin\controllers;

use app\modules\index\filters\PermissionFilter;
use common\models\Menu;
use common\models\RoleAuth;
use yii\base\Exception;
use yii\web\Controller;
use common\models\Admin;
use common\models\Role;

class AdminController extends Controller{

    public $layout = false;
    public $enableCsrfValidation=false;
    public function __construct ($id, $module, $config = [])
    {
        $module = \Yii::$app->getModule('admin');
        parent::__construct($id, $module, $config);
    }
    public function behaviors()
    {
        return [
            [
                'class' => PermissionFilter::className()
            ]
        ]; // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {        
        if (\Yii::$app->request->isPost) {
            $post = \Yii::$app->request->post();
            $list = Admin::getleftrole($post);
        }else{
            $list = Admin::getleftrole();
            $post = array('user_name'=>'');
        }
        $page=$list['page'];
        $data=$list['data'];
        return $this->render('index.tpl',array('data'=>$data,'page'=>$page,'post'=>$post));

    }
    public function actionAdd(){
        if (\Yii::$app->request->isPost) {
            $post = \Yii::$app->request->post();
            $model = new Admin();
            if(empty($post['user_id'])){
                //添加轮播图
                $model->password = setpassword('123456');
                $model->user_name = $post['user_name'];
                $model->real_name = $post['real_name'];
                $model->mobile = $post['mobile'];
                $model->status = $post['status'];
                $model->role_id = $post['role_id'] ? $post['role_id'] : 0;
                $model->create_time = time();
                $result = $model->insert(false);
            }else{
                $list = Admin::getone($post['user_id']);
                if(empty($list)){
                    return $this->goBack('index');
                }
                $post['update_time'] = time();
                $result = Admin::Admin_update($post['user_id'],$post);
            }
            return $this->goBack('index');
        }
        $data['list'] = Role::getList();
        if(\Yii::$app->request->isGet){
            $list = \Yii::$app->request->get();
            if($list){
                $data['data'] = Admin::getone($list['id']);
                if(empty($data['data'])){
                    throw new UserException('管理员不存在！');
                }
                return $this->render('add.tpl',$data);
            }
        }
        $data['data'] = array(
            'user_name'=>'',
            'real_name'=>'',
            'mobile'=>'',
            'status'=>1,
            'role_id'=>'',
            'user_id'=>'',
        );
        return $this->render('add.tpl',$data);
    }
    //添加角色
    public function actionAddrole()
    {
        if(posts())
        {
            $post=posts();
//            var_dump($post);die();
            // 开始事务
            $tr = \Yii::$app->db->beginTransaction();
            try
            {
                $res=Role::selectrole($post['role_name']);
                if(!$res)
                {
                    throw new Exception('已存在该用户');
                }
                $role_id=Role::addrole($post);
//                var_dump($role_id);die();
                $data['role_id']=$role_id;
                foreach ($post['menu_id'] as $item=>$value)
                {
//                    echo $value;
                    $data['menu_id']=$value;
                    RoleAuth::addroleauth($data);
                }
//                die();
                // 提交事务
                $tr->commit();

            }
            catch(\Exception $e)
            {
                // 回滚事务
                $tr->rollBack();
                var_dump($e->getMessage());die();
            }
            return $this->redirect('/admin/admin/index');

        }
        $data['list'] = Menu::getList();
//        var_dump($data['list']);
        return $this->render('addrole.tpl',$data);
    }
    public function actionList(){
        if (\Yii::$app->request->isAjax) {
            $get = \Yii::$app->request->post();
            
            $list = Admin::getInfo(array('user_name'=>$get['user_name']));
            $response = \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            if($list){
                return [
                    'success'=>0,
                    'list'=>$list,
                ];
            }else{
                return [
                    'success'=>1,
                    'list'=>$list,
                ];
            }
        }
    }
    //重新设置密码
    public function actionNewpassword(){
        if (\Yii::$app->request->isAjax) {
            $get = \Yii::$app->request->post();
            $response = \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            $list = Admin::getone($get['user_id']);
            if($list){
                $password = setpassword('123456');
                $result = Admin::Updatepassword($get['user_id'],$password);
                if($result){
                    return [
                    'success'=>1,
                    'data'=>'重新设置密码成功',
                ];
                }else{
                    return [
                    'success'=>0,
                    'data'=>'重新设置密码失败',
                ];
                }
            }else{
                return [
                    'success'=>0,
                    'data'=>'账号不存在',
                ];
            }
        }
    }
}