<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/9/20
 * Time: 15:06
 */

namespace common\models;


use yii\db\ActiveRecord;
use yii\db\Query;

/**
 * This is the model class for table "leave_message".
 *
 * @property int $message_id 留言内容ID
 * @property int $banquet_id 对应流水席ID
 * @property int $order_id 对应席单ID
 * @property int $user_id
 * @property string $service_score 流水席评分
 * @property string $message_detail 留言内容
 * @property string $image_url 留言图片路径
 * @property int $message_time 留言时间
 */

class LeaveMessage extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%leave_message}}'; // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['banquet_id', 'order_id', 'user_id'], 'required'],
            [['banquet_id', 'order_id', 'user_id', 'message_time'], 'integer'],
            [['service_score'], 'number'],
            [['message_detail'], 'string'],
            [['image_url'], 'string', 'max' => 255],
        ];
    }

    /**
     * @param string $banquet_id 流水席的id
     * @return array
     * 获取流水席的评价信息
     */
    public static function getComment($banquet_id ='',$page=0)
    {
        $pageSize = 10;
        if (empty($banquet_id)) {
            return [];
        }
        $query = new Query();
        $query->select('lm.service_score,lm.message_detail,lm.message_time,u.user_name,u.nickname,u.image_path')->from(LeaveMessage::tableName().'lm');
        $query->leftJoin(User::tableName().'u','u.user_id = lm.user_id');
        $query->where(['lm.banquet_id'=>$banquet_id]);
        $query->orderBy('lm.message_time DESC');
        $query->limit($pageSize)->offset($page*$pageSize);
        return $query->all();
    }

    /**
     * @param string $banquet_id
     * @return int
     * 得到评分总数
     */
    public static function getCountScore ($banquet_id ='')
    {
        if (empty($banquet_id)) {
            return 0;
        }
        $query = new Query();
        $query->select('Sum(service_score) as service_score')->from(LeaveMessage::tableName().'lm');
        $query->where(['banquet_id'=>$banquet_id]);
        $rs = $query->one();
        return $rs['service_score'];
    }

    public static function getCountNumber($banquet_id){
        $query = new Query();
        $query->select('count(*) as count')->from(LeaveMessage::tableName().'lm');
        $query->where(['lm.banquet_id'=>$banquet_id]);
        $result=$query->one();
        if (!empty($result)) {
            return ceil($result['count']/10);
        }else{
            return 0;
        }

    }
}