<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/9/22
 * Time: 15:39
 */

namespace frontend\controllers;


use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

class DefaultController extends Controller
{
    public function behaviors()
    {
        return [
            [
                //附加行为frontend\components
                'class' => \frontend\components\CheckLoginBehavior::className(),
            ]
        ]; // TODO: Change the autogenerated stub
    }

//    public function behaviors()
//    {
//        $this->CheckLogin();
//        return [];
//    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

//    public function CheckLogin()
//    {
//        $session=\Yii::$app->session;
//        $openid = $session->get('openid');
//        $user_id = $session->get('user_id');
//        $sign=makeSignature(['openid' => $openid,'user_id' => $user_id,'sign' => 'cqzgkjlsx'],'cqzgkjlsx');
//        if ($session->get($openid.'lsx') !== $sign) {
//            return $this->redirect(homeurl('site/login'));
//        }
//    }

}