<?php

namespace app\modules\region\controllers;

use app\modules\index\filters\PermissionFilter;
use yii\web\Controller;
use common\models\Region;
class RegionController extends Controller{

    public $layout = false;
    public $enableCsrfValidation=false;
    
    public function __construct ($id, $module, $config = [])
    {
        $module = \Yii::$app->getModule('region');
        parent::__construct($id, $module, $config);
    }
    public function behaviors()
    {
        return [
            [
                'class' => PermissionFilter::className()
            ]
        ]; // TODO: Change the autogenerated stub
    }
    public function actionList(){
        if (\Yii::$app->request->isAjax) {
            $get = \Yii::$app->request->post();
            $list = Region::get_parent_code($get['s_province']);
            $response = \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            return [
                'list'=>$list,
            ];
        }
    }
}