<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/9/12
 * Time: 9:27
 */
namespace app\modules\marketing\controllers;

use app\modules\index\filters\PermissionFilter;
use yii\web\Controller;
use common\models\Marketing;
use common\models\UserOrder;
use common\models\BackOrder;
use common\helpers\ArrayHelper;
use common\models\MealTicket;
use common\models\Shop;
class MarketingController extends Controller{

    public $layout = false;

    public function __construct ($id, $module, $config = [])
    {
        $module = \Yii::$app->getModule('marketing');
        parent::__construct($id, $module, $config);
    }
    public function behaviors()
    {
        return [
            [
                'class' => PermissionFilter::className()
            ]
        ]; // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
        if (\Yii::$app->request->isPost) {
            $post = \Yii::$app->request->post();
//            if($post['name']){
//                $list = Shop::getlist($post);
//                $amount=Shop::Marketing_ticket_amount('amount',$post);
//            }else{
//                $list = Marketing::getlist($post);
//                $amount=Marketing::Marketing_ticket_amount('amount',$post);
//            }
            $list = Marketing::getlist($post);
            $amount=Marketing::Marketing_ticket_amount('amount',$post);
        }else{
            $list = Marketing::getlist();
            $amount=Marketing::Marketing_ticket_amount('amount');
            $post = array('add_time_begin'=>'','add_time_end'=>'','name'=>'','ticket_status'=>'');
        }
        $page=$list['page'];
        $data=$list['data'];
        
        $user_order = '';//订单号
        $back_order = '';//退单号
        if(!empty($data))
        {
            foreach($data as $val){
                if($val['ticket_status'] == 0 || $val['ticket_status'] == 1){
                    $user_order .= $val['ticket_order'].',';
                }
                if($val['ticket_status'] == 2){
                    $back_order .= $val['ticket_order'].',';
                }
            }
        }

        $user_order = rtrim($user_order, ",");
        $back_order = rtrim($back_order, ",");
        $user_order_list = array();
        if($user_order){
            $user_order_list = UserOrder::find()->select('record_id,record_sn')->where('record_id in ('.$user_order.')')->asArray()->all();
        }
        $back_order_list = array();
        if($back_order){
            $back_order_list = BackOrder::find()->select('return_id,return_sn')->where('return_id in ('.$back_order.')')->asArray()->all();  
        }
        $user_order_list = $user_order_list ? ArrayHelper::user_order_keyid($user_order_list) : '';
        $back_order_list = $back_order_list ? ArrayHelper::back_order_keyid($back_order_list) : '';
        return $this->render('index.tpl',array('amount'=>$amount ? $amount : 0,'data'=>$data,'page'=>$page,'user_order_list'=>$user_order_list,'back_order_list'=>$back_order_list,'post'=>$post));

    }
    public function actionFanpiaojine(){
        if (\Yii::$app->request->isPost) {
            $cookie = \Yii::$app->request->cookies;
            $user_id = $cookie->getValue('user_id');
            $post = \Yii::$app->request->post();
            $model = new MealTicket();
            $model->ticket_price = trim($post['ticket_price']);
            $model->operator_id = $user_id ? $user_id : 1;
            $model->caeate_time = time();
            $result = $model->insert(false);
            if($result){
               return $this->goBack('fanpiaojine'); 
            }
        }else{
            $post = array();
        }
        $data = MealTicket::getList();
        $page=$data['page'];
        $data=$data['data'];
        $reset = reset($data);

        return $this->render('fanpiaojine.tpl',array('data' => $data ,'reset' => $reset ,'page' => $page ,'post' => $post));
    }
}