<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/10/11
 * Time: 16:42
 */

namespace frontend\components;


use common\models\User;
use yii\base\ActionFilter;
use yii\web\Controller;

class CheckLoginBehavior extends ActionFilter
{
    public function beforeAction($action)
    {
        $session=\Yii::$app->session;
        $openid = $session->get('openid');
        $user_id = $session->get('user_id');
        $model = new Controller('','', $config = []);
        $url =\Yii::$app->request->getUrl();
        if (empty($openid) || empty($user_id)) {
            return $model->redirect(homeurl('site/login'));
        }
        $sign=makeSignature(['openid' => $openid,'user_id' => $user_id,'sign' => 'cqzgkjlsx'],'cqzgkjlsx');
        if ($session->get($openid.'lsx') !== $sign) {
            \Yii::$app->getSession()->setFlash('redirectUrl', $url);
            return $model->redirect(homeurl('site/login'));
        }
        $status = User::find()->select('user_status')->where(['openid' =>$openid])->one();
        if ($status->user_status == 0) {
            $session->removeAll();
            $session->destroy();
            throw new \yii\base\UserException('你的账号已被禁用');
        }
        return true; // TODO: Change the autogenerated stub
    }
}