<?php
namespace app\modules\account\controllers;
error_reporting(0);

use app\modules\index\filters\PermissionFilter;
use common\report\Daochu;
use yii\web\Controller;
use common\models\Region;
use common\models\ShopAccount;
use common\models\ShopRecord;
use common\models\ShopAccountDetail;
use common\report\Cell;
use common\report\ColReport;
class AccountController extends Controller{

    public $layout = false;
    public $enableCsrfValidation=false;

    public function __construct ($id, $module, $config = [])
    {
        $module = \Yii::$app->getModule('account');
        parent::__construct($id, $module, $config);
    }
    public function behaviors()
    {
        return [
            [
                'class' => PermissionFilter::className()
            ]
        ]; // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
//        $cookie = \Yii::$app->request->cookies;
//        $name=$cookie->getValue('admin_name');
//        var_dump($name);die;
        $region_code[0]['parent_code'] = '';
        $region_code_new[0]['parent_code'] = '';
        if (\Yii::$app->request->isPost) {
            $post = \Yii::$app->request->post();
            $region_code = Region::get_region_code($post['s_city']);
            $region_code_new = Region::get_region_code($post['s_county']);
            if($post['s_county']){
                $post['region_code'] = $post['s_county'];
                $post['leve'] = 3;
            }elseif($post['s_city'] && $post['s_county'] ==''){
                $post['region_code'] = $post['s_city'];
                $post['leve'] = 2;
            }elseif($post['s_province'] && $post['s_city'] == '' && $post['s_county'] ==''){
                $post['region_code'] = $post['s_province'];
                $post['leve'] = 1;
            }
            $list = ShopAccount::getlist($post);
        }else{
            $list = ShopAccount::getlist();
            $post = array('add_time_begin'=>'','add_time_end'=>'','name'=>'','s_province'=>'','s_city'=>'','s_county'=>'');
        }
        $data = fenye($list['list']);
        $level = Region::getlist('1');//城市一级
//        $parent_code_one = $region_code[0]['parent_code'] ? $region_code[0]['parent_code'] : '50';//城市二级
        $parent_code_one = $region_code[0]['parent_code'] ? $region_code[0]['parent_code'] : '';//城市二级
//        $parent_code_two = $region_code_new[0]['parent_code'] ? $region_code_new[0]['parent_code'] : '50,01';//城市三级
        $parent_code_two = $region_code_new[0]['parent_code'] ? $region_code_new[0]['parent_code'] : '';//城市三级
        $parent_code_one = Region::get_parent_code($parent_code_one);
        $parent_code_two = Region::get_parent_code($parent_code_two);
        return $this->render('index.tpl',array('list'=>$list,'data'=>$data['data'],'page'=>$data['page'],'level'=>$level,'parent_code_one'=>$parent_code_one,'parent_code_two'=>$parent_code_two,'post'=>$post));

    }
    public function actionShenqingtixian(){
        if (\Yii::$app->request->isPost) {
            $post = \Yii::$app->request->post();
            $data = ShopRecord::getlist($post);
        }else{
            $data = ShopRecord::getlist();
            $post = array('add_time_begin'=>'','add_time_end'=>'','name'=>'','request_status'=>'');
        }
        $page=$data['page'];
        $data=$data['data'];
        return $this->render('shenqingtixian.tpl',array('data' => $data ,'post' => $post ,'page' => $page));
    }
    public function actionRefuse(){
        if(\Yii::$app->request->isPost) {
            $post = \Yii::$app->request->post();
            $list = ShopRecord::getone($post['request_id']);
            $cookie = \Yii::$app->request->cookies;
            $user_id = $cookie->getValue('user_id');
            if($list['request_status'] == 0){
                $post['request_status'] = 2;
                $post['update_time'] = time();
                $post['approve_id'] = $user_id ? $user_id : 1;
                $result = ShopRecord::record_update($list['request_id'],$post);
                if($result){
                    return $this->goBack('shenqingtixian'); 
                }
            }else{
                return $this->goBack('shenqingtixian');
            }
        }
    }
    public function actionAdopt(){
        if(\Yii::$app->request->isGet) {
            $get = \Yii::$app->request->get();
            $list = ShopRecord::getone($get['request_id']);
            $shop_msg = ShopAccount::find()->select('total_balnce,request_blance')->where('shop_id='.$list->shop_id.'')->one(); 
            if($list->request_amount>$shop_msg->total_balnce) {
                throw new UserException('该店铺余额不足，不能提现！');die;
            }
            if($list['request_status'] == 0){
                $post['request_status'] = 1;
                $post['update_time'] = time();
                $post['approve_id'] = 1;
                $post['content'] = '';
                $result = ShopRecord::record_update($list['request_id'],$post);
                if($result){
                    ShopAccount::updateAll([
                                    'total_balnce' => $shop_msg->total_balnce-$list->request_amount,
                                    'request_blance' => $shop_msg->request_blance+$list->request_amount,
                                    'withdraw_amount' => $shop_msg->withdraw_amount+$list->request_amount,
                                    'update_time' => time()
                                ], [
                                    'shop_id' => $list->shop_id
                                ]);
                    $modeldetail = new ShopAccountDetail();
                    $modeldetail->account_status = 3;
                    $modeldetail->acount_amount = '-'.$list->request_amount;
                    $modeldetail->account_order = $list->request_id;
                    $modeldetail->shop_id = $list->shop_id;
                    $modeldetail->caeate_time = time();
                    $result = $modeldetail->insert(false);
                    return $this->goBack('shenqingtixian'); 
                }
            }else{
                return $this->goBack('shenqingtixian');
            }
        }
    }
    public function actionExport ()
	{
                $post = \Yii::$app->request->get();
                if($post['s_county']){
                    $post['region_code'] = $post['s_county'];
                }elseif($post['s_city'] && $post['s_county'] ==''){
                    $post['region_code'] = $post['s_city'];
                }elseif($post['s_province'] && $post['s_city'] == '' && $post['s_county'] ==''){
                    $post['region_code'] = $post['s_province'];
                }
                $filter = ShopAccount::getlist($post);
		$cols = [];
		
		$cols[] = Cell::create('shop_name', '商家名称', 0);
		$cols[] = Cell::create('region_name', '地区', 0);
		$cols[] = Cell::create('banquet_orders', '席单总数', 0);
		$cols[] = Cell::create('sales_amount', '销售总额（元）', 0);
		$cols[] = Cell::create('total_balnce', '账户余额', 0);
		$cols[] = Cell::create('withdraw_amount', '已提现总额', 0);
		$cols[] = Cell::create('platform_amount', '平台佣金', 0);
        $cols[] = Cell::create('commission_rate', '当前分佣比例（%）', 0);
		$report = new ColReport($cols);
		$i = 0;
		foreach($filter['list'] as $item)
		{
			$report->setCellValue(Cell::toId($i + 1, 'shop_name'), $item['shop_name']);
			$report->setCellValue(Cell::toId($i + 1, 'region_name'), $item['region_name']);
			$report->setCellValue(Cell::toId($i + 1, 'banquet_orders'), $item['banquet_orders']);
			$report->setCellValue(Cell::toId($i + 1, 'sales_amount'), $item['sales_amount']);
			$report->setCellValue(Cell::toId($i + 1, 'total_balnce'), $item['total_balnce']);
			$report->setCellValue(Cell::toId($i + 1, 'withdraw_amount'), $item['withdraw_amount']);
			$report->setCellValue(Cell::toId($i + 1, 'platform_amount'), $item['platform_amount']);
			$report->setCellValue(Cell::toId($i + 1, 'commission_rate'), $item['commission_rate']);
			$i++;
		}
		
		$report->setTitle('财务管理统计');
		
		$res=$report->toExcel(true);
	}

	public function actionDaochu ()
    {
        if(\Yii::$app->request->isGet){
            $post = \Yii::$app->request->get();
            if($post['s_county']){
                $post['region_code'] = $post['s_county'];
            }elseif($post['s_city'] && $post['s_county'] ==''){
                $post['region_code'] = $post['s_city'];
            }elseif($post['s_province'] && $post['s_city'] == '' && $post['s_county'] ==''){
                $post['region_code'] = $post['s_province'];
            }
            $filter = ShopAccount::getlist($post);
//            var_dump($filter);die;
            $title = '财务管理-'.time();
            $head = array('商家名称','地区','席单总数','销售总额（元）','账户余额','已提现总额','平台佣金','当前分佣比例（%）');
            $cow_index = array('shop_name','region_name','banquet_orders','sales_amount','total_balnce','withdraw_amount','platform_amount','commission_rate');
            Daochu::daochu($head,$filter['list'],$title,$cow_index);
        }
    }

    /**
     * 提现记录导出
     */
    public function actionExportWithdrawals ()
    {
            $post = \Yii::$app->request->get();
            $filter = ShopRecord::getlist($post,true);
             $title = '提现记录-'.time();
             $head = array('商家名称','店主手机号','申请提现金额','状态','申请日期','审核日期','操作者','姓　名','银行卡号','开 户 行');
             $cow_index = array('shop_name','merchant_mobile','request_amount','request_status','request_time','update_time','user_name','withdraw_name','bank_account','withdraw_bank');
             foreach ($filter as $key=>$item)
             {
                 if ($item['request_status'] == 0) {
                     $filter[$key]['request_status']=' 待审核';
                }elseif ($item['request_status'] == 1) {
                     $filter[$key]['request_status']='审核通过';
                }elseif ($item['request_status'] == 2){
                     $filter[$key]['request_status']='审核未通过';
                }
                $filter[$key]['request_time']= date('Y-m-d h:i:s',$item['request_time']);
                 $filter[$key]['update_time']= date('Y-m-d h:i:s',$item['update_time']);
             }
             Daochu::daochu($head,$filter,$title,$cow_index);
//             echo '<pre/>';
//             var_dump($filter);die();
//            $cols = [];
//
//            $cols[] = Cell::create('shop_name', '商家名称', 0);
//            $cols[] = Cell::create('merchant_mobile', '店主手机号', 0);
//            $cols[] = Cell::create('request_amount', '申请提现金额', 0);
//            $cols[] = Cell::create('request_status', '状态', 0);
//            $cols[] = Cell::create('request_time', '申请日期', 0);
//            $cols[] = Cell::create('update_time', '审核日期', 0);
//            $cols[] = Cell::create('admin_name', '操作者', 0);
//            $cols[] = Cell::create('withdraw_name', '姓　名', 0);
//            $cols[] = Cell::create('bank_account', '银行卡号', 0);
//            $cols[] = Cell::create('withdraw_bank', '开 户 行', 0);
//            $report = new ColReport($cols);
//            $i = 0;
//            foreach($filter as $item)
//            {
//                $report->setCellValue(Cell::toId($i + 1, 'shop_name'), $item['shop_name']);
//                $report->setCellValue(Cell::toId($i + 1, 'merchant_mobile'), $item['merchant_mobile']);
//                $report->setCellValue(Cell::toId($i + 1, 'request_amount'), $item['request_amount']);
//                if ($item['request_status'] == 1) {
//                    $report->setCellValue(Cell::toId($i + 1, 'request_status'), '申请中');
//                }elseif ($item['request_status'] == 2) {
//                    $report->setCellValue(Cell::toId($i + 1, 'request_status'), '审核通过');
//                }elseif ($item['request_status'] == 3){
//                    $report->setCellValue(Cell::toId($i + 1, 'request_status'), '审核未通过');
//                }
//                $report->setCellValue(Cell::toId($i + 1, 'request_time'), date('Y-m-d h:i:s',$item['request_time']));
//                $report->setCellValue(Cell::toId($i + 1, 'update_time'), date('Y-m-d h:i:s',$item['update_time']));
//                $report->setCellValue(Cell::toId($i + 1, 'admin_name'), $item['user_name']);
//                $report->setCellValue(Cell::toId($i + 1, 'withdraw_name'), $item['withdraw_name']);
//                $report->setCellValue(Cell::toId($i + 1, 'bank_account'), $item['bank_account']);
//                $report->setCellValue(Cell::toId($i + 1, 'withdraw_bank'), $item['withdraw_bank']);
//                $i++;
//            }
//
//            $report->setTitle('商家提现申请统计');
//
//            $res=$report->toExcel(true);
    }
}