<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/9/12
 * Time: 9:27
 *商家中心首页
 */
namespace app\modules\shop\controllers;


use common\models\BanquetOrder;
use common\models\Shop;
use yii\db\Query;
use yii\web\Controller;

class CenterController extends Controller
    {
    public function init ()
    {
        $sadhnsq = new \seller\controllers\InitController;
        $sadhnsq->actionClassName();
    }
    //public function behaviors()
    //{
    //    return [
    //        'class' => $init_class = new \seller\controllers\InitController();
        //$init_class->actionClassName();
    //    ]; // TODO: Change the autogenerated stub
    //}
    public $layout = 'main.tpl';

    //public function __construct ($id, $module, $config = [])
    //{
    //    $module = \Yii::$app->getModule('user');
    //    parent::__construct($id, $module, $config);
    //}
    //商家中心菜单页面
    public function actionIndex (){
        $session = \Yii::$app->session; 
        $shop_usermsg = $session->get('seller_msg');
        if($shop_usermsg['shop_id']){
            $date = date('Y-m-d');
            $date_min =strtotime($date);
            $date_max= $date_min+86400;
             $banquet_msg_list = BanquetOrder::find()->select('order_price,joined_peoples')->where('shop_id='.$shop_usermsg['shop_id'].' and order_status=3 and create_time>'.$date_min.' and create_time<'.$date_max.'')->asArray()->groupBy('order_id')->all();
             $banquet_msg['total_moeny'] = 0;
             $banquet_msg['total_order'] = 0;
             if($banquet_msg_list) {
                foreach ($banquet_msg_list as $value) {
                    $banquet_msg['total_moeny']+=($value['order_price']*$value['joined_peoples']);
                }
                 $banquet_msg['total_moeny'] = sprintf("%.2f", substr(sprintf("%.3f", floatval($banquet_msg['total_moeny'])), 0, -1));
                 $banquet_msg['total_order'] = count($banquet_msg_list);
             }
             $shop_name = Shop::find()->select('shop_name')->where('shop_id='.$shop_usermsg['shop_id'].'')->asArray()->one();
        }
        $params['banquet_msg'] = $banquet_msg;
        $params['shop_name'] = $shop_name;
        return $this->render('index.tpl',$params);
    }

}