<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/9/12
 * Time: 9:27
 */
namespace app\modules\shop\controllers;

use yii\base\ActionFilter;
use yii\web\Controller;
use yii\helpers\Url;

class CompareController extends ActionFilter {

public function beforeAction($action)
{
	$session = \Yii::$app->session;
    if(!$session->get('user_id')) {
    	return \Yii::$app->getResponse()->redirect(Url::to(array('/user/login/index')), 302);
    	// return $this->redirect(array('/user/login/index'));
    }else{
    	return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}

}